# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt6 UI code generator 6.8.0.dev2410211537
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(435, 681)
        MainWindow.setMinimumSize(QtCore.QSize(434, 681))
        MainWindow.setStyleSheet("QWidget {\n"
"    color: white;\n"
"    background-color: #121212;\n"
"    font-family: Rubik;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.label.setFont(font)
        self.label.setStyleSheet("color: #888;")
        self.label.setMidLineWidth(2)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.le_enty = QtWidgets.QLineEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_enty.sizePolicy().hasHeightForWidth())
        self.le_enty.setSizePolicy(sizePolicy)
        self.le_enty.setStyleSheet("font-size: 40pt;\n"
"border: none;")
        self.le_enty.setMaxLength(10)
        self.le_enty.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.le_enty.setReadOnly(True)
        self.le_enty.setObjectName("le_enty")
        self.gridLayout_9.addWidget(self.le_enty, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.C = QtWidgets.QPushButton(parent=self.centralwidget)
        self.C.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.C.setFont(font)
        self.C.setStyleSheet("\n"
"QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.C.setObjectName("C")
        self.gridLayout_4.addWidget(self.C, 0, 2, 1, 1)
        self.CE = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CE.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.CE.setFont(font)
        self.CE.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.CE.setObjectName("CE")
        self.gridLayout_4.addWidget(self.CE, 0, 1, 1, 1)
        self.prosent = QtWidgets.QPushButton(parent=self.centralwidget)
        self.prosent.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.prosent.setFont(font)
        self.prosent.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.prosent.setObjectName("prosent")
        self.gridLayout_4.addWidget(self.prosent, 0, 4, 1, 1)
        self.steret = QtWidgets.QPushButton(parent=self.centralwidget)
        self.steret.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.steret.setFont(font)
        self.steret.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.steret.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Downloads/backspace_34dp_FFFFFF_FILL0_wght400_GRAD0_opsz40.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.steret.setIcon(icon)
        self.steret.setIconSize(QtCore.QSize(24, 24))
        self.steret.setObjectName("steret")
        self.gridLayout_4.addWidget(self.steret, 0, 6, 1, 1)
        self.history = QtWidgets.QPushButton(parent=self.centralwidget)
        self.history.setMinimumSize(QtCore.QSize(80, 80))
        self.history.setObjectName("history")
        self.gridLayout_4.addWidget(self.history, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.root_koren_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self.root_koren_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.root_koren_.setFont(font)
        self.root_koren_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.root_koren_.setObjectName("root_koren_")
        self.gridLayout_3.addWidget(self.root_koren_, 0, 2, 1, 1)
        self.delenie = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delenie.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.delenie.setFont(font)
        self.delenie.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.delenie.setObjectName("delenie")
        self.gridLayout_3.addWidget(self.delenie, 0, 3, 1, 1)
        self.x_in_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.x_in_2.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.x_in_2.setFont(font)
        self.x_in_2.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.x_in_2.setObjectName("x_in_2")
        self.gridLayout_3.addWidget(self.x_in_2, 0, 1, 1, 1)
        self._1_na_x = QtWidgets.QPushButton(parent=self.centralwidget)
        self._1_na_x.setEnabled(True)
        self._1_na_x.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._1_na_x.setFont(font)
        self._1_na_x.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._1_na_x.setObjectName("_1_na_x")
        self.gridLayout_3.addWidget(self._1_na_x, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._9_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self._9_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._9_.setFont(font)
        self._9_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._9_.setObjectName("_9_")
        self.gridLayout_2.addWidget(self._9_, 0, 2, 1, 1)
        self.mnogenie = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mnogenie.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.mnogenie.setFont(font)
        self.mnogenie.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.mnogenie.setObjectName("mnogenie")
        self.gridLayout_2.addWidget(self.mnogenie, 0, 3, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self._8_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self._8_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._8_.setFont(font)
        self._8_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._8_.setObjectName("_8_")
        self.gridLayout.addWidget(self._8_, 0, 0, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self._7_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self._7_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._7_.setFont(font)
        self._7_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._7_.setObjectName("_7_")
        self.gridLayout_2.addWidget(self._7_, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self._6_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self._6_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._6_.setFont(font)
        self._6_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._6_.setObjectName("_6_")
        self.gridLayout_7.addWidget(self._6_, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.minus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minus.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.minus.setFont(font)
        self.minus.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.minus.setObjectName("minus")
        self.gridLayout_5.addWidget(self.minus, 0, 3, 1, 1)
        self._5_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self._5_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._5_.setFont(font)
        self._5_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._5_.setObjectName("_5_")
        self.gridLayout_5.addWidget(self._5_, 0, 1, 1, 1)
        self._4_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self._4_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._4_.setFont(font)
        self._4_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._4_.setObjectName("_4_")
        self.gridLayout_5.addWidget(self._4_, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self._3_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self._3_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._3_.setFont(font)
        self._3_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._3_.setObjectName("_3_")
        self.gridLayout_6.addWidget(self._3_, 0, 2, 1, 1)
        self.plus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.plus.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.plus.setFont(font)
        self.plus.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.plus.setObjectName("plus")
        self.gridLayout_6.addWidget(self.plus, 0, 4, 1, 1)
        self._2_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self._2_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._2_.setFont(font)
        self._2_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._2_.setObjectName("_2_")
        self.gridLayout_6.addWidget(self._2_, 0, 1, 1, 1)
        self._1_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self._1_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._1_.setFont(font)
        self._1_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._1_.setObjectName("_1_")
        self.gridLayout_6.addWidget(self._1_, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self._0_ = QtWidgets.QPushButton(parent=self.centralwidget)
        self._0_.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self._0_.setFont(font)
        self._0_.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self._0_.setObjectName("_0_")
        self.gridLayout_8.addWidget(self._0_, 0, 1, 1, 1)
        self.ne_seloe = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ne_seloe.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.ne_seloe.setFont(font)
        self.ne_seloe.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.ne_seloe.setIconSize(QtCore.QSize(50, 50))
        self.ne_seloe.setObjectName("ne_seloe")
        self.gridLayout_8.addWidget(self.ne_seloe, 0, 2, 1, 1)
        self.ravno = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ravno.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.ravno.setFont(font)
        self.ravno.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.ravno.setObjectName("ravno")
        self.gridLayout_8.addWidget(self.ravno, 0, 3, 1, 1)
        self.plus_or_minus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.plus_or_minus.setMinimumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.plus_or_minus.setFont(font)
        self.plus_or_minus.setStyleSheet("QPushButton:hover {\n"
"    background-color: #666;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}")
        self.plus_or_minus.setObjectName("plus_or_minus")
        self.gridLayout_8.addWidget(self.plus_or_minus, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 435, 23))
        self.menubar.setObjectName("menubar")
        self.menuCalculato = QtWidgets.QMenu(parent=self.menubar)
        self.menuCalculato.setObjectName("menuCalculato")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCalculato.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.le_enty.setText(_translate("MainWindow", "0"))
        self.C.setText(_translate("MainWindow", "C"))
        self.CE.setText(_translate("MainWindow", "CE"))
        self.prosent.setText(_translate("MainWindow", "%"))
        self.history.setText(_translate("MainWindow", "History"))
        self.root_koren_.setText(_translate("MainWindow", "√х"))
        self.delenie.setText(_translate("MainWindow", "÷"))
        self.x_in_2.setText(_translate("MainWindow", "x²"))
        self._1_na_x.setText(_translate("MainWindow", "1/x"))
        self._9_.setText(_translate("MainWindow", "9"))
        self.mnogenie.setText(_translate("MainWindow", "X"))
        self._8_.setText(_translate("MainWindow", "8"))
        self._7_.setText(_translate("MainWindow", "7"))
        self._6_.setText(_translate("MainWindow", "6"))
        self.minus.setText(_translate("MainWindow", "-"))
        self._5_.setText(_translate("MainWindow", "5"))
        self._4_.setText(_translate("MainWindow", "4"))
        self._3_.setText(_translate("MainWindow", "3"))
        self.plus.setText(_translate("MainWindow", "+"))
        self._2_.setText(_translate("MainWindow", "2"))
        self._1_.setText(_translate("MainWindow", "1"))
        self._0_.setText(_translate("MainWindow", "0"))
        self.ne_seloe.setText(_translate("MainWindow", "."))
        self.ravno.setText(_translate("MainWindow", "="))
        self.plus_or_minus.setText(_translate("MainWindow", "+/-"))
        self.menuCalculato.setTitle(_translate("MainWindow", "Обычный"))
